spring.application.name=Ticket Service

grpc.server.port=9090

spring.database.url=jdbc:postgresql://localhost:5432/tickets
spring.database.username=ticket_user
spring.database.password=ticket_password
spring.database.driver-class-name=org.postgresql.Driver

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml